### ISSUE TITLE
Ammonite-Ops doesn't handle multiple drives on windows

### ISSUE THREAD

**Issue by lihaoyi** [lihaoyi/Ammonite#120]
Currently it assumes every absolute path is relative to the process working directory's root drive. Although expedient, it does not work in the general case. We should figure out exactly how we need to change the datastructure to make it work across drives.

**Comment by mnn** [comment]
Ehm, this is _enhancement_? Because of this issue whole library is pretty much unusable on Windows - I can't even get path from command arguments b/c if I get absolute path bad things happen. I'm pretty sure this is a **deal-breaking bug** for many potential users, not just an improvement or enhancement...

**Comment by mnn** [comment]
I wanted to try quickly hack in the Win path root support, but after finding out that many tests are failing and some even freezing I changed my mind. I am appending logs and looking for alternatives.

Details:
- Win 10 Pro
- i5
- 16GB RAM (around 10GB free during testing)
- SSD (tested on non-system partition)
- installed mingw (binaries like `bash` and `ls` are in path)

REPL test was killed after running nearly **ONE HOUR**, fully stressing the CPU whole time.

[test_integration.txt](https://github.com/lihaoyi/Ammonite/files/129274/test_integration.txt)
[test_ops.txt](https://github.com/lihaoyi/Ammonite/files/129273/test_ops.txt)
[test_repl__killed_after_1h.txt](https://github.com/lihaoyi/Ammonite/files/129276/test_repl__killed_after_1h.txt)
[test_shell.txt](https://github.com/lihaoyi/Ammonite/files/129272/test_shell.txt)
[test_terminal.txt](https://github.com/lihaoyi/Ammonite/files/129275/test_terminal.txt)

**Comment by lihaoyi** [comment]
The fact that the Ammonite REPL doesn't work on Windows is well known https://github.com/lihaoyi/Ammonite/issues/119. Of course the unit tests don't work. If it did all work, I wouldn't have two "Doesn't work" issues on the issue tracker!

If you actually want help making it work you made a ton of rookie software engineering mistakes and I could help if you're interested. If you're just interested in being a jerk I can't really help you.

**Comment by mnn** [comment]
#119 doesn't really imply freezing tests. Also not only REPL is broken, actually **every batch of tests but one is failing**.

As you wrote, I am a rookie - new to SBT, to team collaboration, to Ammonite (used your library only once for a toy project). So you can understand I am not keen to start digging into something I know nothing about. Not only I know nothing about it, I can't really even start hacking into it, because if I inevitably break something, tests won't tell me...

I suggest you state on project's main page that the library is currently incompatible with most used OS (honestly didn't expect this).

**If you want running more tests, I can do that.** But I think I really can't help with Windows paths implementation until at least ops tests not related to paths are fine (e.g. not matching compile error messages, something weird with probably character encoding, it seems the tests depend on some shell scripts inside repo [why? IMO Ammonite should be usable even without other shell], but I might be wrong).

If I was a real jerk, I would not fork and clone repo, I would not run tests, I would not **wait for an hour** and I would not post results. I would just rage-write a message in one minute, gloated and moved on.

Please see this from my perspective - I saw a **Rock-solid shell scripting** library which is **broken on most popular operating system** and there is not even a word about it on project page. Then I try to add the support myself only to find out that almost every group of tests is failing. I was looking for a working solution (something to write short scripts in) and was happy to see I could try it in my favorite language (I'm not a fan of Bash, batch files, Ruby or Python). I wasn't looking for another pet project I probably won't have time for...

**Comment by lihaoyi** [comment]
@mnn Honestly your perspective is rather odd. 

- You clearly came in expected it to be some trivial fix for somebody new-to-everything to make it work on windows. If it was so trivial to make it work, it would already have happened! 

- You're unhappy it doesn't work on windows, but you really shouldn't be surprised, because that's exactly what these issues are tracking!

- It is a mistake letting yourself get worked up by a piece of software not working. Things don't do what you expect sometimes. It's not the end of the world

- It's silly to waste so much time trying to get something working without, well, asking someone (we have a chat room for a reason!)

Anyway, I'm gonna go up and delete your posts on this issue (and mine) since they're mostly unconstructive ranting. Feel free to re-post without all the rage =)

**Comment by mnn** [comment]
It's not rage, I was just explaining my position (English is not my
native language, so if it sounded aggressive I'm sorry, it was not my
intent). According to
http://www.codenameone.com/blog/developer-promotion-practical-guide-statistics-about-the-java-echo-system.html
**52%** of Java developers are using Windows. Not sure if Scala
developers differ that much, but I doubt it. I believe you should
reconsider the not informing about supported OSes thing. Honestly, when
I come to a library (or any project) page I read primarily the main page
(possibly sub-pages involving installation and dependencies, if links
are present). Reading tens or even hundreds of issues is IMO not common.
I don't think one should read all open and closed issues to discover
limitations and dependencies of any project. But it is just my opinion.

> If it was so trivial to make it work, it would already have happened!

From the issues I got the (maybe wrong) impression that you have limited
access to a machine with Windows and that's the main reason for not
supporting it yet (judging from contribution page it's safe to say you
are the master contributor - 92 thousands line changes, second after you
got only 2 thousands).

I wish you and the project well (I quite like it). Maybe you get more
help if you stop calling people jerks, even thought they ran broken
tests for an hour and shared results ;-).

My offer of running more tests stands, if you are interested. If you
need any more info about my environment or hw I'd be happy to respond.

(This message probably deserves a delete as well.)

**Comment by lihaoyi** [comment]
@mnn yeah the issue tracker isn't the place for this kind of chatter and meta-discussion. Bring it to the gitter channel =)

**Comment by lihaoyi** [comment]
The first Windows CI build for Ammonite-Ops has passed

https://ci.appveyor.com/project/lihaoyi/ammonite

**Comment by lihaoyi** [comment]
Non-mutable link: https://ci.appveyor.com/project/lihaoyi/ammonite/build/14
