### ISSUE TITLE
Repl prepends whitespaces to wrapped lines causing issues with select+copy

### ISSUE THREAD

**Issue by nkvoll** [lihaoyi/Ammonite#205]
The Repl prepends `prompt.size` whitespace characters to the beginning of new visual input lines (after soft wrapping). This makes it impossible (or dangerous) to copy using select + copy previous input from one shell to another because the contents may have changed depending on the terminal width and prompt size.

Consider this example: (using a short terminal width):

    @ val foo = "lorem ipsum and the r
      est lorem ipsum and the rest lor
      em ipsum and the rest lorem ipsu
      m and the rest lorem ipsum and t
      he rest lorem ipsum and the rest
      "
    foo: String = "lorem ipsum and the
     rest lorem ipsum and the rest lor
    em ipsum and the rest lorem ipsum 
    and the rest lorem ipsum and the r
    est lorem ipsum and the rest"
    @

Copying the first val (selecting everything from the first `"` to the last `"` from the input) results int he following string `"lorem ipsum and the r  est lorem ipsum and the rest lor  em ipsum and the rest lorem ipsu  m and the rest lorem ipsum and t  he rest lorem ipsum and the rest  "` (notice the double-spaces added).

**Comment by lihaoyi** [comment]
Yep this is a problem. This is even worse for code, because the random spaces will probably break whatever snippet you were running and it won't even compile.

Here's a solution that I just found: Fish Shell does this pretty neat thing:

<img width="829" alt="screenshot 2015-08-30 01 28 14" src="https://cloud.githubusercontent.com/assets/934140/9568450/1567c71e-4efe-11e5-9051-e7504b120706.png">

Where if your command takes more than one line, they kick it to the next line below the prompt and have it start from the far left. This preserves both the "normal" single-line experience, provides a properly-aligned multi-line experience, and allows correct C&P.

**Comment by nkvoll** [comment]
That sounds like a sensible solution :)

**Comment by lihaoyi** [comment]
This continues to annoy me
