### ISSUE TITLE
Streams are realized

### ISSUE THREAD

**Issue by cvogt** [lihaoyi/Ammonite#21]
Try `Stream.iterate(1)(_+1)`. The repl tries to fully realize the stream leading to infinite output. Not sure what's better, Scala REPL's no-info or ammonite's non-termination. Preview of just a few values would be nice.

**Comment by lihaoyi** [comment]
Yeah, this is kinda intentional. The goal was to give long, streaming operations (e.g. subprocess output, `ls! root`) a chance to stream into the console. The exact mechanism is still up for debate, but the original plan was to make the REPL realize these streams, so that they appear in the repl as the computation progresses and yet are still available after to use in further computations. Now that I have `ls!! root !!` to create an iterator and force it, not sure how necessary it still is...

**Comment by cvogt** [comment]
having played with it a bit more... I think it is actually ok to realize the stream, you an always interrupt it unlike with the normal repl

**Comment by cvogt** [comment]
Closing this for now
