### ISSUE TITLE
ammonite.sshd.SshdReplTest.canExecuteRemoteCommand is super flaky

### ISSUE THREAD

**Issue by lihaoyi** [lihaoyi/Ammonite#211]
Seems to be failing about 1/4 of builds, as seen https://travis-ci.org/lihaoyi/Ammonite/builds/79034260. @dant3 any idea what we could do about it? Not sure if it's just being slow or whether we need to add some retriees

**Comment by dant3** [comment]
It seems like Travis is very slow at executing repl. I think [This guy can be removed](https://github.com/lihaoyi/Ammonite/blob/master/sshd/src/test/scala/ammonite/sshd/SshdReplTest.scala#L32), because we are waiting then repl will exit anyway (also checks that `exit` works actually), but if closing the ssh session times out as well the only thing can be done here is increasing the timeout value.

**Comment by lihaoyi** [comment]
Cutting out the timeout seems to have made the problem go away, for now...
