### ISSUE TITLE
Import resolution problem

### ISSUE THREAD

**Issue by dant3** [lihaoyi/Ammonite#248]
Here is an example code that makes importing scala._ stuff impossible:

```scala
object importing_issue {
  object scala {
    def evilThing = ???
  }
}

import scala.concurrent.duration._
import importing_issue._
println("foo")
```

which results in:
```
Compilation Failed
Main.scala:49: value concurrent is not a member of object cmd1.importing_issue.scala
import scala.concurrent.duration.{
             ^
Main.scala:93: value None is not a member of object cmd1.importing_issue.scala
              .print(res3, res3, "res3", scala.None)
                                               ^
```

and makes your repl useless.

**Comment by lihaoyi** [comment]
This is tricky; we could probably make it work by maintaining the `previousImports` map as ordered by insertion. We'd also need to keep multiple imports from the same namespace separate rather than collapsing them into the same import statement, to support cases like

```scala
import scala.concurrent
object import_issue{
  object scala{
    def evilThing = ???
  }
}
import importing_issue._
import scala.evilThing
```

Which will take some elbow-grease, but doesn't seem in-principle difficult
