### ISSUE TITLE
Pretty Print not showing consistent output with Range (object, class)

### ISSUE THREAD

**Issue by Saheb** [lihaoyi/Ammonite#287]
@ (1 to 10)
res3: collection.immutable.Range.Inclusive = Range(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)

@ Range(1,10)
res4: Range = Range(1, 2, 3, 4, 5, 6, 7, 8, 9)

@ (1 until 10)
res5: Range = Range(1, 2, 3, 4, 5, 6, 7, 8, 9)

**Comment by lihaoyi** [comment]
This looks like expected behavior to me. collections are serialized based on `stringPrefix` or something, intentionally, not based on their compile-time type. There are many many cases where these two things will differ, e.g.

```scala
@ Vector(1, 2, 3): Seq[Int]
res0: Seq[Int] = Vector(1, 2, 3)
```

And the different range expressions are different types

```scala
@ typeOf(0 until 10)
res3: reflect.runtime.package.universe.Type = scala.collection.immutable.Range
@ typeOf(0 to 10 )
res4: reflect.runtime.package.universe.Type = scala.collection.immutable.Range.Inclusive
```

Why? I'm not sure. I would have thought they could return the same type, from an encapsulation point of view it doesn't seem necessary to tell everyone `"look I'm not just a normal range, I'm inclusive!!!"`. Nevertheless, that's the semantics the standard library gives us, and given that Ammonite is already doing the right thing

**Comment by Saheb** [comment]
@ 1 to 10
res4: Range.Inclusive = Range(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)

Doesn't think look pretty? I know its not just about pretty :)
Not sure if I have a better argument, but as collection.immutable is already in scope, then woundn't be a good idea to remove it. 

I was just tweeking around the TPrintLowPri macro to understand how it works and encountered this.

**Comment by lihaoyi** [comment]
That's plausible. Feel free to send a PR!
