### ISSUE TITLE
REPL - Syntax highlighting in 256 colorspace does not reset (since 0.5.4)

### ISSUE THREAD

**Issue by HaydenSikh** [lihaoyi/Ammonite#369]
When assigning ANSI escape codes for custom colors during REPL syntax highlighting, color codes outside of the basic color range are rendered but not terminated at syntax boundary.

For example, "\033[38;5;67m" is the ASNI code for a light blue in the 256 colorspace.  If starting Ammonite from SBT REPL using the following command:
```scala
ammonite.repl.Main.run("""repl.colors().keyword() = "\033[38;5;67m"""")
```

then when typing:
```scala
val x = "foo"
```

the light blue color is extended over the `val x =` until the start of the string changes the color again.  Prior to v0.5.5, or if using a simpler code like `Console.BLUE` or the equivalent `\033[34m` then the color is only extended over the `val` as expected.

**Comment by lihaoyi** [comment]
Looks like our [AnsiStr](https://github.com/lihaoyi/Ammonite/blob/master/terminal/src/main/scala/ammonite/terminal/Ansi.scala#L50-L67) implementation does not understand any colors outside the basic range, or that they need to be escaped. 

A workaround would be to change the `prompt()` rather than `colors().keyword()`, which would let you manually append the `Console.RESET` to the end.

The full solution would be to extend the linked code to understand all 256 colors as part of the foreground/background color list. How widely is this 256-color thing supported?

**Comment by HaydenSikh** [comment]
I believe most terminals come with 256 color support these days unless they're specifically trimmed down server builds.  As a quick and dirty check, doing `echo $TERM` on both my local OS X install and a vanilla AWS Ubuntu instance gives back `xterm-256color`.

**Comment by lihaoyi** [comment]
ok good to know. Shouldn't be hard to make this work

**Comment by lihaoyi** [comment]
fixed in master with the move to the Fansi color-string library
