### ISSUE TITLE
parent of root directory should be root

### ISSUE THREAD

**Issue by HongxuChen** [lihaoyi/Ammonite#385]
It seems that Ammonite treats "parent of root directory" as an error ([Path.scala](https://github.com/lihaoyi/Ammonite/blob/62a22244172eb20ce9cd3df5e0f715c9751d8cb5/ops/src/main/scala/ammonite/ops/Path.scala#L147-L148)); however a conventional shell in Linux/Mac OS X, usually treats it as the root directory.

**Comment by lihaoyi** [comment]
What's the use case for this, though? 

This was an explicit design decision to be less forgiving than normal shells, in order to have better control of what's happening, and more aggressive throwing of exceptions rather than trying to "carry on". 

I could be convinced to change my mind, but I would take some convincing

**Comment by HongxuChen** [comment]
@lihaoyi Actually I cannot think of a reasonable scenario. I just feel that a regular shell had better follow the convention; and in this case, I think perhaps simply silent this error (or only displaying a warning) should be more preferable.

Anyway, this is personal favor.

**Comment by lihaoyi** [comment]
ok closing this for now, feel free to reopen and talk more i you feel strongly
