### ISSUE TITLE
Documentation is extremely hyped

### ISSUE THREAD

**Issue by paulp** [lihaoyi/Ammonite#43]
"It is much more featureful than the default REPL ... Ammonite-REPL supports many more features than the default REPL"

I propose that delivering feature parity - and working at all - should take place before making grandiose claims of this kind. I might be unusually conservative in that regard. Here's some completion from the scala repl:
```
scala> List(1)
res0: List[Int] = List(1)

scala> res0.map<tab>
map   mapConserve

scala> res0.map<tab> // it elaborates
   def map[B, That](f: A => B)(implicit bf: generic.CanBuildFrom[List[A],B,That]): That

scala> java.lang.String.valueOf<tab>
                                             def valueOf(Boolean): String   def valueOf(Int): String
def valueOf(Any): String                     def valueOf(Char): String      def valueOf(Long): String
def valueOf(Array[Char]): String             def valueOf(Double): String
def valueOf(Array[Char], Int, Int): String   def valueOf(Float): String
```
Ammonite offers the method name, that's it.

The signature the repl gives for map is wrong (it's a List[Int] so the A should have been substituted to Int) so there's an opportunity for you to actually improve on it. You only hurt your credibility with the glib claims, and frankly there's plenty of room for humility when you only got imports sort of working a few hours ago.

Even your chosen example output has issues. It suggests "scala.concurrent.Future$class" and then acts like it has never heard of it.
```
@ scala.concurrent.Future<tab>
Future             FutureTaskRunner
```

**Comment by lihaoyi** [comment]
That one issue is already tracked under https://github.com/lihaoyi/Ammonite/issues/26. I can fix the `$class` stuff.

Being worse in some ways doesn't mean you're not better in others ^_^ I'm already using Ammonite's REPL daily for various things (including work) so it's plenty usable, and things like colored/pretty-printed output, autocomplete-in-anonymous-functions, infinite-loop-interruptability, and other things makes it a superior experience to me as is.

I don't think I can ever hope for credibility in your eyes, and for the vast majority with lower standards I think saying Ammonite has more features isn't unreasonable even if it has bugs (not like the current REPL doesn't ^_^).

I'm going to fix-forward rather than rolling back that text, and will close this issue when I satisfy the things you've brought up

**Comment by paulp** [comment]
If the scala repl is full of bugs, which of course it is, that's all the more reason to put the Mission Accomplished banner in the closet until there aren't so many potential deal-breakers for anyone who took the description at face value.

Credibility has nothing to do with the quality of your code by the way. The worst programmer still has credibility if they accurately depict their software, and the dual to that statement should be obvious. If you can't ever hope for credibility in my eyes that's pretty sad, because all it requires is forthrightness.

**Comment by lihaoyi** [comment]
You think you require forthrightness, but I think you actually require quite a lot more ^_^ 

Different people value different things. You may think "getting imports from Scalaz" working is basic functionality, I think "being able to interrupt infinite loops" is much more basic than that, especially for the (real) work I've been using Ammonite for. You think that type-signatures-on-autocomplete is basic, and I think that autocompleting non-trivial fragments *at all* is even more basic.

And so I think Ammonite-REPL is best in class, and you think it's not. And that's totally OK with me.

**Comment by lihaoyi** [comment]
wontfix
