### ISSUE TITLE
IntelliJ support for Ammonite scripts

### ISSUE THREAD

**Issue by lihaoyi** [lihaoyi/Ammonite#434]
IntelliJ supports `.sc` files, kinda-sorta: it treats them as worksheets. This means that it provides that annoying interactive/right-hand-pane, as well as not supporting `import  $ivy` and `import $file` syntax.

We should teach IntelliJ how to understand our `.sc` scripts, including imports. Whether as a separate plugin or as patches to the main IntelliJ-Scala plugin

@coderabhishek took a look at this over the summer for GSOC, but will not have time to do it this summer.

@Alefas who works on the IntelliJ-Scala had the following advice, for anyone who wants to take up this cup:

> Any changes are welcome. And we always open to help to anybody, who wants to contribute.
> 
> You need to implement two things:
> 1. Runtime, so worksheet should be compiled with additional imports.
> 2. IDE resolve to see additional imports.
> 
> For the first one take a look for `org.jetbrains.plugins.scala.worksheet.processor.WorksheetSourceProcessor`
> It's class, which generates code for the following compilation. So you will need just to add few more imports to the header.
> 
> For the second one take a look for `org.jetbrains.plugins.scala.lang.psi.api.FileDeclarationsHolder#processDeclarations`
> I think you should do the following:
> After ImportHolder processing you should add processing for the synthetic imports, which you can generate with `org.jetbrains.plugins.scala.lang.psi.impl.ScalaPsiElementFactory`
> 
> Please ask me, if you need any help with your task.

**Comment by Miuler** [comment]
Seria fantástico poder agregar una cabecera al estilo:
  `#!/usr/bin/env amm`

It would be great to be able to add a header to the style:
  `#!/usr/bin/env amm`

**Comment by ysusuk** [comment]
Hi guys, i'm working on the issue. As for now i managed to make `import $file.` compile, and have some basic code completion

<img width="1074" alt="screen shot 2016-12-25 at 15 56 29" src="https://cloud.githubusercontent.com/assets/1115934/21524451/70c7c7e8-cd16-11e6-83a8-bbc57a389086.png">

<img width="1074" alt="screen shot 2016-12-25 at 15 56 48" src="https://cloud.githubusercontent.com/assets/1115934/21524456/75f0152c-cd16-11e6-9f16-f08009a4c398.png">

**Comment by olafurpg** [comment]
Hello! I have also looked at this issue and would like to share my modest progress so far. I felt kinda unproductive in the intellij-scala repo. The handling of `.sc` files is complicated in order to print out the value of each intermediary expression, which I don't really care about for ammonite scripts.

Instead, I created a fresh project for a custom intellij-ammonite plugin. The repo is here: https://github.com/olafurpg/intellij-ammonite

What does it do? The sbt build is setup so that you can run `sbt pluginRun` to start a fresh intellij installation with the plugin installed. All the plugin currently does is to add a new "Ammonite" file type for `.amm` file extensions. `.amm` files are just like regular scala files except with support to put statements in the top-level (no need to wrap in object/class). Demo:

<img width="423" alt="screen shot 2017-01-07 at 17 33 49" src="https://cloud.githubusercontent.com/assets/1408093/21743332/1eb65090-d500-11e6-89ef-766e5b7b7126.png">

`$file/$ivy` imports still get red squiggly marks. I am personally most motivated to get `$ivy` working. My current plan is to use the ammonite api to extract the classfiles loaded from `$ivy` imports. Once we have a `Seq[File]` of classfiles, I think it should be possible to use the intellij api to index all the symbols.

**Comment by lihaoyi** [comment]
Yeah, we don't really need the worksheet-style behavior. 

I wouldn't worry about using `.amm` for the extension in your plugin. If it works out, it shouldn't be too hard to override the default plugin handler with yours somehow, either ourselves or with the help of the IntelliJ people who could provide hooks.

**Comment by olafurpg** [comment]
I may have celebrated too fast, it seems `sbt pluginRun` has some cache issues. It doesn't always include the most recent edits.

BTW, the intellij-ammonite repo is just to make it easier/faster to experiment with this idea. It's possible to do the same thing in intellij-scala, but that repo is quite heavy to work with.  If anything comes out of this experiment, I think it would be best to try and merge it back into intellj-scala. The real challenge is to find the correct intellij-scala internal api incantations.

**Comment by drdozer** [comment]
See also:

https://youtrack.jetbrains.com/issue/SCL-10752

**Comment by lihaoyi** [comment]
There's a vote button on that IntelliJ issue; if anyone is reading this and wants it to happen, take a moment to go vote so the jetbrains folks know we care 😄

**Comment by ysusuk** [comment]
Hi guys, want to give some new info. Just recently talked to Dmitry Naydanov from Intellij team. He gave me some ideas how to patch compile server to run ammonite in case of ammonite scripts. So no need to patch WorksheetSourceProcessor that i did in my first try. Will keep you up to date!

**Comment by lihaoyi** [comment]
Cool!

Personally, I do not care much about *running* code in IntelliJ, though I understand others might. My workflow is to use IntelliJ for editing and do all the running in the terminal, so my hopes are for someone to make all these red squigglies go away and give me autocomplete 😛  

<img width="596" alt="screenshot 2017-01-11 22 46 59" src="https://cloud.githubusercontent.com/assets/934140/21852948/07db3bc6-d850-11e6-8206-20624e75e9d5.png">

**Comment by ysusuk** [comment]
@lihaoyi i must agree. i always running them from terminal

**Comment by drdozer** [comment]
My workflow a the moment is to have a script, hack/run it and then start pulling out the plumbing into an sbt project that produces a JAR. So being able to load that all up in a single IDE session, cut-paste code from scripts into scala sources in the project that becomes the jar would be great. But 90% of the red I have is because of $ivy and $file imports. If those were addressed, I'd be happy.

**Comment by jbyler** [comment]
I'm glad there's progress on this--thanks ysusuk!

My preference though would be to change the syntax to make ammonite scripts be valid Scala, though, since that solution would work for all IDEs, plus editors like vim, emacs, sublime ...  With the current syntax the work of supporting ammonite scripts has to be repeated from scratch for each IDE / editor.

**Comment by Habitats** [comment]
Any update on this?

**Comment by PerArneng** [comment]
This would be very useful. Thanks

**Comment by drdozer** [comment]
Any progress? Right now I'm getting red for the one-line ammonite script

```
import ammonite.ops._
```

**Comment by amirkarimi** [comment]
+1 for making ammonite scripts be valid Scala. Like:
```
ammoniteImport.ivy("com.amazonaws:aws-java-sdk-ecs:1.11.76")
```
instead of 
```
import $ivy.`com.amazonaws:aws-java-sdk-ecs:1.11.76`
```

**Comment by carueda** [comment]
Just to comment that the current <code>import $ivy.&#96;com.amazonaws:aws-java-sdk-ecs:1.11.76&#96;</code> construct better conveys the intended compile-time effect.

**Comment by nhenin** [comment]
Any progress ?

**Comment by piotrkwiecinski** [comment]
@nhenin Jetbrains is working on it and looks like there will be something in 2017.3 which is in public preview. Here is a list of stuff that is done/remaining: https://youtrack.jetbrains.com/issues/SCL?q=%23Ammonite%20

**Comment by DavidPerezIngeniero** [comment]
Is nearly all fixed! :-)

**Comment by time2die** [comment]
Good day ! Is it normal behavior of idea and script.sc file ?
![image](https://user-images.githubusercontent.com/519303/34003078-66afd166-e105-11e7-8e88-0a4b4be6661a.png)

**Comment by DavidPerezIngeniero** [comment]
Have you associated .sc extesion to Ammonite?.  It may be treated as a Scala worksheet.
For me, it works as a charm.

**Comment by carueda** [comment]
@DavidPerezIngeniero  How were you able to have Ammonite as an option for the file association? I have the latest 2017.3.1 but still not seeing that.

**Comment by DavidPerezIngeniero** [comment]
Hola Carlos

Got to Settings and select Always process .sc as Ammonite.
See screenshot
![image](https://user-images.githubusercontent.com/6008104/34093542-17121a94-e3c9-11e7-869a-382e1d2a3a15.png)

**Comment by carueda** [comment]
Gracias @DavidPerezIngeniero

**Comment by einnocent** [comment]
For those having trouble, this may be helpful:

![screen shot 2017-12-18 at 9 58 55 pm](https://user-images.githubusercontent.com/356718/34142909-b08d5cb8-e43e-11e7-8a88-da64e267ddb5.png)

https://blog.jetbrains.com/scala/2017/11/28/intellij-idea-scala-plugin-2017-3-lightbend-project-starter-ammonite-support-parallel-indexing-and-more/

**Comment by einnocent** [comment]
I'm still having trouble getting this to work, so I started a [Stack Overflow question](https://stackoverflow.com/questions/48002919/how-to-get-intellij-to-recognize-imports-in-scala-script).

**Comment by lihaoyi** [comment]
Seems like this has happened
