### ISSUE TITLE
Code runs OK in REPL but fails when compiled as script 

### ISSUE THREAD

**Issue by jk-1** [lihaoyi/Ammonite#481]
Following code runs OK in amm REPL but fails when compiled as script:

```
val home = root/RelPath(System.getenv("HOME").substring(1))
val dir = home/'tmp/'amm/'bckp
val fileSeq = ls! dir
println(fileSeq);
val dirSeq : Seq[Path] = fileSeq.sorted |? ( f => f.isDir)
val dirSeq2 = dirSeq |? grep! "[0-9][0-9]".r
println(dirSeq2);
```

It gives following compilation error:

```
exp01.sc:17: type mismatch;
found   : ammonite.runtime.tools.grep.![scala.util.matching.Regex]
 required: ammonite.ops.Path => Boolean
val dirSeq2 = dirSeq |? grep! "[0-9][0-9]".r    
```

**Comment by ckampfe** [comment]
@jk-1 I was able to get this to compile and run after importing
`import ammonite.ops._` and `import pprint.Config.Defaults._`.

I got the idea for the pprint import from [here](https://github.com/lihaoyi/Ammonite/blob/3ccb6b18cd5a18ce63070b2179884995125aaa57/amm/src/test/scala/ammonite/ToolsTests.scala). I believe this is due to changing what is loaded in scripts in version [0.7.2](http://www.lihaoyi.com/Ammonite/#0.7.2).

The APIs available by default in the REPL and in scripts is different, so some imports have changed.

**Comment by lihaoyi** [comment]
Yes, you have to `import ammonite.ops._` if you want ammonite ops APIs

As for `grep`, that's probably more meant for the REPL than in scripts. I have thus removed it from the script imports in https://github.com/lihaoyi/Ammonite/commit/b8fb39b94f7ecbc90508875bd92ff15ea14fb59d, which should avoid the confusing error message

**Comment by lihaoyi** [comment]
http://www.lihaoyi.com/Ammonite/#0.9.0 is out
