### ISSUE TITLE
Providing credentials for resolver

### ISSUE THREAD

**Issue by Eli-Golin** [lihaoyi/Ammonite#483]
Hi... Is there a possibility to specify credentials for a custom resolver?
If there's, could you provide an example of that?

**Comment by lihaoyi** [comment]
There isn't right now AFAIK; it shouldn't be hard to add, but you'll need to fiddle with the ivy stuff. Relevant code here https://github.com/lihaoyi/Ammonite/blob/3ccb6b18cd5a18ce63070b2179884995125aaa57/amm/runtime/src/main/scala/ammonite/runtime/tools/IvyThing.scala#L208

**Comment by bkempe** [comment]
Adding 
```scala
org.apache.ivy.util.url.CredentialsStore.INSTANCE.addCredentials(realm, host, username, password)
```
before the resolution seems to be a workaround.

**Comment by lihaoyi** [comment]
Now that https://github.com/lihaoyi/Ammonite/issues/491 is fixed in https://github.com/lihaoyi/Ammonite/commit/daa476809a8307586dca30703ae7e7f8fba74ab8, you should be able to use Coursier's `Repository` APIs to add credentials to a particular repository, as described in https://github.com/coursier/coursier#api-1:

```scala

import coursier.core.Authentication

interp.repositories() ++= Seq(MavenRepository(
  "https://nexus.corp.com/content/repositories/releases",
  authentication = Some(Authentication("user", "pass"))
))

```

This should go out in the next version sometime this weekend

**Comment by lihaoyi** [comment]
http://www.lihaoyi.com/Ammonite/#0.9.0 is out
