### ISSUE TITLE
import $file with files that have another extension other than sc

### ISSUE THREAD

**Issue by alfonsomunozpomer** [lihaoyi/Ammonite#494]
Hi, is it possible to import scripts that have an extension other than `sc` using the `import $file` syntax?

I can do:
```
interp.load.module(Path(pwd + "/Blah.scala")) 
Compiling Main.sc
...
```

But if I try with `import $file` I get:
```
import $file.`Blah.scala`
Cannot resolve $file import: /Users/amunoz/Blah.scala
```

Which is a bit baffling because the file actually exists. All those errors go away if I rename the file to `Blah.sc` and use `import $file.Blah`.

**Comment by lihaoyi** [comment]
Can't import anything but `.sc` files right now; i doubt this will change because it would complicate file import resolution and reduce the quality of the error messages. Most scripting languages like Python or Ruby are similar IIRC: you can have your main script called whatever you want, but the imported scripts need the right extension

**Comment by alfonsomunozpomer** [comment]
Then a better message aother than:
```
Cannot resolve $file import: /Users/amunoz/Blah.scala
```

Would be helpful. Maybe add the `sc` extension?
```
Cannot resolve $file import: /Users/amunoz/Blah.scala.sc
```
