### ISSUE TITLE
ammonite for scala 2.12.0

### ISSUE THREAD

**Issue by stuhood** [lihaoyi/Ammonite#501]
Hello! We're interested in using ammonite (the repl in particular) with scala 2.12.0, but aren't familiar enough with the sbt build to help cross publish it. Would love to see a new release when possible!

**Comment by lihaoyi** [comment]
@stuhood there's some WIP in the `2.12` branch. It's not a trivial cross-publish because Ammonite depends on sketchy compiler internals, which have changed in 2.12. I have it compiling, but there's still some tests failing due to unknown reasons which will take more time to sort out.

If you have any free engineering time/engineers to help out, `sbt ++2.12.0 amm/test` should reveal a bunch of reds... otherwise I'll get to it eventually

**Comment by lihaoyi** [comment]
Seems like `ammonite.CachingTests.processModuleCaching.testLoadModule` is unhappy

**Comment by lihaoyi** [comment]
The problem with `testLoadModule` seems to be that the classfiles in the `dynamicClasspath: VirtualDirectory`:

- https://github.com/lihaoyi/Ammonite/blob/2.12/amm/interp/src/main/scala/ammonite/runtime/Compiler.scala#L103

Are not being picked up by Scalac. They're definitely there, and I can print them out and see them, but maybe they're in the wrong format? It's basically "manually" copying the files over to the `dynamicClasspath` after each compilation:

- https://github.com/lihaoyi/Ammonite/blob/2.12/amm/interp/src/main/scala/ammonite/runtime/Compiler.scala#L287

With `writeDeep` being defined as:

- https://github.com/lihaoyi/Ammonite/blob/2.12/amm/runtime/src/main/scala/ammonite/runtime/Evaluator.scala#L216-L225

Perhaps the format of the "stuff" in the VirtualDirectory has changed?

**Comment by jhnsmth** [comment]
I think it's related to how packages  are represented in the VirtualDirectory.  Since
`import $file.myscript`
works perfectly fine, but
`import $file.somefolder.anotherfolder.myscript`
fails with "object myscript is not a member of package anotherfolder". Probably because Scala compiler changed classpath from recursive to flat representation see [SI-9709](https://issues.scala-lang.org/browse/SI-9709).

**Comment by lihaoyi** [comment]
@jhnsmth yeah that's my guess. @lrytz you know stuff about the "flat" classpath representation right? Any idea how that may cause problems with someone trying to use a `VirtualDirectoryClasspath` to initialize the compiler?

**Comment by lrytz** [comment]
yes, that rings a bell.. i don't have time right now to look into it, sorry.. maybe compare the two implementations? in 2.11.x

```
abstract class ClassPath[T] {
  def packages: IndexedSeq[ClassPath[T]]
}
```

there's a new `ClassPath` object for every package

in 2.12.x

```
trait ClassPath {
  private[nsc] def packages(inPackage: String): Seq[PackageEntry]
}
```

there's a single `ClassPath` instance, the `packages` method takes an owner package string as argument. note that the method is not public - i don't remember why exactly.

**Comment by lihaoyi** [comment]
@lrytz thanks for the hints! Will take  look, no worries if you don't have time

Where I am right now is that I can print out the contents of my `dynamicClasspath: VirtualDirectory`, and it has all the classfiles and packages I want:

```scala
    def enumerateVdFiles(d: VirtualDirectory): Iterator[AbstractFile] = {
      val (subs, files) = d.iterator.partition(_.isDirectory)
      files ++ subs.map(_.asInstanceOf[VirtualDirectory]).flatMap(x =>
        Iterator(x) ++ enumerateVdFiles(x)
      )
    }
initGlobalBits:151 enumerateVdFiles(dynamicClasspath).toVector    Vector(
  (memory)/ammonite,
  (memory)/ammonite/predef,
  (memory)/ammonite/predef/interpBridge.class,
  (memory)/ammonite/predef/interpBridge$.class,
  (memory)/ammonite/predef/predef$.class,
  (memory)/ammonite/predef/predef.class,
  (memory)/$file,
  (memory)/$file/amm,
  (memory)/$file/amm/src,
  (memory)/$file/amm/src/test,
  (memory)/$file/amm/src/test/resources,
  (memory)/$file/amm/src/test/resources/scriptLevelCaching,
  (memory)/$file/amm/src/test/resources/scriptLevelCaching/testLoadModule.class,
  (memory)/$file/amm/src/test/resources/scriptLevelCaching/testLoadModule$.class,
  (memory)/$file/amm/src/test/resources/scriptLevelCaching/scriptToBeLoaded.class,
  (memory)/$file/amm/src/test/resources/scriptLevelCaching/scriptToBeLoaded$.class
)
```

but if I try to use `lookupName` on one of those packages, it fails:

```scala
initGlobalBits:152 dynamicClasspath.lookupName("$file/amm", directory = true)	null
```

It seems `lookupName` is being called from `getSubdir` as part of the compilation process with the string `"$file/amm"`, which is the first point I've noticed something going wrong. From what I can tell, it's calling `getSubDir` first on `"$file"`, then `"$file/amm"`, which then fails and it doesn't proceed further. Presumably if it succeeded it would go all the way in and then find the package/class we want it to find (`"$file/amm/src/test/resources/scriptLevelCaching/testLoadModule.class"`). 


Currently, `getSubDir` just does a raw `lookupName`, which as far as I can tell only does a shallow lookup to try and find the thing it wants. It seems that `getSubDir` should be fixed in the same way `findClassFile` was in https://github.com/scala/scala/pull/5544, by making it recursively traverse the `VirtualDirectory` tree rather than doing a shallow lookup of the direct children

**Comment by lihaoyi** [comment]
Cool this made a bunch more tests pass:

```scala
   val dynamicCP = new VirtualDirectoryClassPath(dynamicClasspath){
      override def getSubDir(packageDirName: String): Option[AbstractFile] = {
        val pathParts = packageDirName.split('/')
        var file: AbstractFile = dir
        for (dirPart <- pathParts) {
          file = file.lookupName(dirPart, directory = true)
          if (file == null) return None
        }
        Some(file)

      }
      override def findClassFile(className: String): Option[AbstractFile] = {
        pprint.log(className)
        val relativePath = FileUtils.dirPath(className)
        val pathParts = relativePath.split('/')
        var file: AbstractFile = dir
        for (dirPart <- pathParts.init) {
          file = file.lookupName(dirPart, directory = true)
          if (file == null) return None
        }

        file.lookupName(pathParts.last + ".class", directory = false) match {
          case null => None
          case file => Some(file)
        }
      }
    }
```

Onward and upward...

**Comment by lihaoyi** [comment]
Ok everything should be green with 2.12 passing on master; if the build goes well the next unstable release will support 2.12

Notable fixes include:

- Fixing `VirtualDirectoryClassPath` https://github.com/lihaoyi/Ammonite/blob/master/amm/interp/src/main/scala-2.12/ammonite/runtime/CompilerCompatibility.scala#L100-L127

- Blocking scalac from closing my classloaders when I still want to use them https://github.com/lihaoyi/Ammonite/blob/master/amm/runtime/src/main/scala/ammonite/runtime/ClassLoaders.scala#L126-L132

**Comment by lihaoyi** [comment]
This is out in the latest unstable version http://www.lihaoyi.com/Ammonite/#UnstableVersions

<img width="313" alt="screenshot 2016-11-20 12 06 19" src="https://cloud.githubusercontent.com/assets/934140/20460312/e2de7b44-af19-11e6-966b-18329477abf4.png">
