### ISSUE TITLE
There should be an Ammonite script runner for Scala 2.11

### ISSUE THREAD

**Issue by nessus42** [lihaoyi/Ammonite#532]
There should be an Ammonite script runner for Scala 2.11. And maybe one for Scala 2.10, as well.

Not all Scala libraries (especially ones developed locally) are available for Scala 2.12 yet. So it makes sense to have available an Ammonite script runner that uses Scala 2.11.

Also, consider what happens when Scala 2.13 comes out. You don't want downloading the latest version of Ammonite to break all of your existing scripts. A site that uses Ammonite in anger might have dozens or hundreds of Ammonite scripts.

Sure, if I am careful, when I download a new version of Ammonite, I might make sure that I have saved the old version somewhere, and then I could just rename the new version to "amm13", or something, diverting disaster. And then I'd use "amm13" for new scripts, and keep "amm" for old scripts.

But if I haven't thought ahead, I might overwrite "amm" with a version that is incompatible with my existing scripts, and then I'll be in a pickle.

Okay, so in that case I can probably clone the Ammonite Git repository and find a commit that contains a version of Ammonite that will work with my old scripts, and I can build that version. But none of this is very user-friendly, and it can cause a lot of frustration.

This is one reason why Python is distributed in both 2.7 and 3.5 versions. You can use the Python 2.7 version for legacy code and the Python 3.5 version for modern code, and you can easily download both versions from the Python website and have them both live in harmony with each other.

**Comment by lihaoyi** [comment]
For this, we'll need to change this to publish executables for multiple versions:

- https://github.com/lihaoyi/Ammonite/blob/master/ci/build.sc#L110-L159

And then change the `Constants.scala` generation code to pass multiple versions in to the readme:

- https://github.com/lihaoyi/Ammonite/blob/master/ci/build.sc#L33-L39

And then change the readme to provide download instructions for the alternate Ammonite executables... somewhere. I'd say chuck it down under the [Reference](http://www.lihaoyi.com/Ammonite/#Reference) section under it's own `Scala 2.10/2.11 Executables` header, with a bit of blurb saying that this only applies to the standalone executable and that the SBT integration should work without any changes (since it already uses whatever Scala version SBT uses)

In addition, we should also publish 2.10/2.11 executables for the [Unstable Versions](http://www.lihaoyi.com/Ammonite/#UnstableVersions) of Ammonite. The download instructions for those can go under the `Unstable Versions` section.

Unfortunately, this CI/CD scripts are a pain in the neck to test, so they'll basically need to be coded up blind. But if anyone wants to take a crack at making the necessary changes to the scripts and readme, I'll work with you to get it working and into master

**Comment by drdozer** [comment]
+1 from me - I'm trying to test out some libraries that currently don't build on 1.12.*

**Comment by lihaoyi** [comment]
This has happened; @jhnsmth started it in #558 and I added it to the docs for 0.8.2

**Comment by nessus42** [comment]
Awesome. Thanks!!!
