### ISSUE TITLE
Enable `args` in script

### ISSUE THREAD

**Issue by ctongfei** [lihaoyi/Ammonite#538]
Is it possible to enable access to `args` variable in code without a function annotated with `@main`?
It'd be good if `args` can be accessed.

**Comment by jtcwang** [comment]
This feature is part of #423 which I'm currently working on.

**Comment by lihaoyi** [comment]
Fixed in https://github.com/lihaoyi/Ammonite/commit/c605d8600c9749b13ade1f85aa6250f959a0a7ff#diff-d624941e18d4c528c725d4c3c0bd0517R1089

This lets `@main` methods with varargs properly slurp in everything, allowing you to then use your own custom argument parser. The only caveat is you cannot use `--` in your own argument list, since that is reserved to separate Ammonite's arguments from your script's arguments. 

Please take a look at the changelog entry which describes this and let me know if this satisfies your requirements

**Comment by lihaoyi** [comment]
http://www.lihaoyi.com/Ammonite/#0.9.0 is out

**Comment by jtcwang** [comment]
Excellent will give it a go. Thanks!
