### ISSUE TITLE
make import ammonite.ops._ default

### ISSUE THREAD

**Issue by antonkulaga** [lihaoyi/Ammonite#569]
I see that in 100% of usages of ammonite I do
```import ammonite.ops._```
and in 90% I also do 
```
import ammonite.ops.ImplicitWd._
```

The situation is the same for my friends who use ammonite. Maybe it makes sence to make them work by default to save time for the most of ammonite users? And if somebody for soma strange reason will decide to get rid of them, then he will just edit the config.

**Comment by giftig** [comment]
Seems counter-intuitive to me to need to explicitly indicate *not* to import it. As well as that, making it a default import would also break a lot of existing scripts which don't import it, largely because some of the imports are likely to clash with other names - and in fact, some of them clash with common java library classes, eg. `Path`, `Readable`, `Bytes`.

`ammonite.ops._` definitely shouldn't be dumped into every script imo.

**Comment by DavidPerezIngeniero** [comment]
e.g. Path clashes with java.nio.file.Path

**Comment by lihaoyi** [comment]
Yeah this is probably not going to happen. If you really want it to, add it to your `predef.sc`. If for some reason `predef.sc` has issues with this use case, we should fix those.

I've personally written plenty of scripts that do not deal with `ammonite.ops`, e.g. instead focusing on things like HTTP/REST calls or using JGit or other third-party libraries, so I don't think this should be the default
