### ISSUE TITLE
Scripts get recompiled even if unchanged

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [lihaoyi/Ammonite#599]
Tried this with Ammonite 0.8.5:

First execution after upgrading Ammonite to version 0.8.5:
```
$ chequea-tunel.scala 
Compiling interpBridge.sc
Compiling defaultPredef.sc
Compiling chequea-tunel.scala
:: loading settings :: url = jar:file:/usr/bin/amm!/org/apache/ivy/core/settings/ivysettings.xml
:: resolving dependencies :: org.scalaj#scalaj-http_2.12-caller;working
        confs: [default]
        found org.scalaj#scalaj-http_2.12;2.3.0 in central
        found org.scala-lang#scala-library;2.12.0 in central
Compiling omd.sc
OK |'redtrust1'=432 'redtrust2'=53 'sapxip'=98 'sapxiq'=94 'firma'=17 'firmapre'=17 'iocweb'=120 'iocwebpre1'=73
```

2nd execution:

```
$ chequea-tunel.scala 
Compiling chequea-tunel.scala
OK |'redtrust1'=490 'redtrust2'=49 'sapxip'=104 'sapxiq'=94 'firma'=17 'firmapre'=19 'iocweb'=99 'iocwebpre1'=84
```

3rd execution:
```
$ chequea-tunel.scala 
Compiling chequea-tunel.scala
OK |'redtrust1'=414 'redtrust2'=50 'sapxip'=101 'sapxiq'=92 'firma'=20 'firmapre'=25 'iocweb'=99 'iocwebpre1'=64
```

Using CentOS 7, 64 bits.

With version 0.8.5 it has improved, because before the `omd.sc` got recompiled also at every execution.

I'll attach the scritpt.

**Comment by DavidPerezIngeniero** [comment]
[chequea-tunel.scala](https://github.com/lihaoyi/Ammonite/files/1000373/chequea-tunel.scala.txt)
[omd.sc](https://github.com/lihaoyi/Ammonite/files/1000374/omd.sc.txt)

Note: I use the .scala extension instead of .sc because IDEA treats .sc as a Scala worksheet.

**Comment by lihaoyi** [comment]
As far as I can tell, your `System.exit` is taking place before the script's compilation results can be saved, which happens only after a script *finishes running* (not just finishes compiling). Furthermore, if a script compiles and runs and fails with an exception, it is also not cached.

*That* is a consequence of the way script execution is interleaved with compilation: when you import a script, Ammonite doesn't have the compiled output before running, because a script may have multiple blocks and all earlier blocks need to execute before later blocks are run. Thus Ammonite needs to wait until the script finishes running, and if you `System.exit` or throw an exception before that, it has no chance to save output.

https://github.com/lihaoyi/Ammonite/issues/437 tracks the rewriting of the import system to avoid this weird interleaved script-compile/script-run behavior, which would then let us pre-compile a script and then save it regardless of any `System.exit`s/exceptions that happen when it is run

**Comment by DavidPerezIngeniero** [comment]
Thanks, now I understand the behaviour much better.

**Comment by DavidPerezIngeniero** [comment]
Confirmed that `System.exit()` is the culprit of continuous recompilation.
