### ISSUE TITLE
Complaint about logging

### ISSUE THREAD

**Issue by hrj** [lihaoyi/Ammonite#607]
> Ammonite now anonymously logs the times you start a REPL session and the count of how many commands get run. This is to allow the author to understand usage patterns and prioritize improvements. If you wish to disable it, pass in the --no-remote-logging command-line flag or the remoteLogging=false argument to Main.

In my opinion, this is not acceptable behaviour for any software, especially not an REPL. When a software does this, I either disable the setting, un-install the software or use a sandbox without internet access.

I hope this feedback allows the author to understand usage patterns and prioritize improvements.

**Comment by lihaoyi** [comment]
If you haven't paid anything for the software, I don't care if you uninstall it =)

If you pay, and people collectively pay enough to support it, I'll remove the logging https://www.patreon.com/lihaoyi

**Comment by hrj** [comment]
I haven't payed (yet) though I appreciate your funding plans.

However, I don't see how that is related to logging (analytics to be precise). That's a bad security practice whether or not the software is free/paid, open/closed.

**Comment by lihaoyi** [comment]
Monetary support is a sign that this software is doing something useful. So is usage statistics.

If you want me to stop collecting usage statistic, I'll happily accept your monetary support as a substitute

**Comment by hrj** [comment]
I don't know where to start; so I will stop.

Thanks for your time.

**Comment by onilton** [comment]
If I understand correctly, this feature can be disabled right? 

The only thing I would suggest is a disclaimer during the install, and explaining the reason why it is enabled by default (supporting development) and why you should not worry about the security of your data.

**Comment by megri** [comment]
I'm not against this but I agree should be more evident to the end-user.

**Comment by fommil** [comment]
I must agree with the original author, remote tracking has been deemed unethical by the Free Software Foundation (as if we needed them to tell us).

That said, you have released this software under a Free/Libre license, so there is nothing stopping somebody else from creating and distributing a version without the tracking.

It is very sad that the Scala developer community (and the very rich developer community in general) are so cheapskate that they cannot sustain the few of us writing the tooling that allows them to get their job done and get paid, but this isn't the way to fix it. I don't know what the answer is, which is why I only write software for me now, and why I use such a brutal form of copyleft when I do it.

**Comment by drhumlen** [comment]
I'm a supporter (through Patreon), and I agree with @onilton!

In fact, I think having usage statistics is probably a great idea 😄 But people take privacy/security extremely seriously and for good reasons. As long as I know that I'm not sending anything that could be considered sensitive, I don't mind this at all. 

Just inform the user upon install / first boot (tiny sentence describing why (and/or a link if you want to read more) + how to disable it if you need extra privacy for some reason).

Very happy with all you work  @lihaoyi . Not just ammonite, but all the other repos too! 😃

**Comment by lihaoyi** [comment]
@drhumlen want to send a PR adding the first-boot message? We already
perform some work on first boot (creating an opaque session file) and ot
shouldnt be hard to print the desired notice to stdout at he same time.

As someone mentioned, making this opt-in would defeat the purpose of this
logging, but better publicizing the opt-out would be fine by me as long as
it's short and not too spammy

**Comment by hrj** [comment]
I received one pertinent technical question [on reddit](https://www.reddit.com/r/scala/comments/6irnix/about_ammonite_tracking_and_why_i_wont_use_it/djdxznj/) and I reproduce my reply here:

> Can you elaborate a bit on what concretely is the security concern?

At a very general level, any app that opens a socket to the outside world is increasing its attack surface. A remote server or man-in-the-middle can inject data that could exploit vulnerabilities in the app, which otherwise wouldn't have been exposed.

Secondly, even if the app just sends some page views to GA, you are giving away your IP address (and thus location), your activity times and the details of your stack to Google (and any other agencies that tie up with Google). As an individual you may not care much about this, but as a professional, consider that the user might be working for a google competitor or in a security-criticial environment. (The onus lies on both the app users to not rely on un-vetted / non-sandboxed software, as well as on app developers to reduce attack surface).

Thirdly, it is a privacy issue. The time I start a shell or perform an action is data that belongs to me. I should be asked for consent before my data is acquired. This is just good form that I expect on part of the developer. I am not sure about legality, but I *think* there are laws in many countries to enforce this as well.

**Comment by simlei** [comment]
I agree with all the security concerns. I just want to post this one, crucial question, because the tone of conversations like this can be viewed by different people very differently:

In spite of viewing this as a security concern, as something shoehorned into our box without consent etc etc. - we all still are thankful to lihaoyi for making this software, right? I am. If no one else does the discalimer at REPL startup, I will eventually. 

I'll also disable the logging "feature" when I build binaries with ammonite that can get onto other's peoples boxes which is just good manners besides the security concern. But still, in doing so, I'll save a load of time becaue I won't have to care about REPL programming, coloring and JVM intricacies as much as I would'e before. So - another time. thanks @lihaoyi. Also, thanks to @hrj for this interesting issue, I wouldn't have been aware of it otherwise.

**Comment by mtavkhelidze** [comment]
```bash
$ echo 'alias amm="amm --no-remote-logging"' >> ~/.bash_profile
```

**Comment by githorse** [comment]
I'm also disconcerted to find out my usage is being reported without my knowledge. I don't actually care if anyone knows how many commands I run, but I don't like finding out about it this way. Regardless of what I paid for the software, it's not in anyone's interest (including the author's) for users to be surprised by potentially alarming behavior that violates standard practice.

Standard practice, at least in my experience, is to prompt the user at install for consent to diagnostics reporting. Why not add a prompt during the install? This would allow the same flexibility as the `--no-remote-logging` feature without alarming Ammonite's users when they find out about this.

**Comment by wind57** [comment]
holly crap! This is _really_ un-expected.
