### ISSUE TITLE
Show java.lang.String as String

### ISSUE THREAD

**Issue by sschaef** [lihaoyi/Ammonite#62]
```scala
> "a b c dtr   fgn".split("\\W+")
res4: scala.Array[java.lang.String] = Array("a", "b", "c", "dtr", "fgn")
```
The Scala Repl shows Strings with their Predef alias.

**Comment by lihaoyi** [comment]
This is hilarious

https://github.com/lihaoyi/Ammonite/blob/master/repl/src/test/scala/ammonite/repl/AdvancedTests.scala#L221-L225

I'm still trying to come up with a good, generic solution to this. Looks like I'm gonna have to recurse over the types and perform the `Type => String` conversion myself

**Comment by lihaoyi** [comment]
This is fixed in the latest merge, with the introduction of the [TPrint[T] typeclass](https://github.com/lihaoyi/Ammonite/blob/master/pprint/src/main/scala/ammonite/pprint/TPrint.scala), which lets you customize type printing but defaults to crawling up the prefix-chain of a dotted type and bailing when any of them exist in scope. The example works

```scala
@ "a b c dtr   fgn".split("\\W+")
res0: Array[String] = Array("a", "b", "c", "dtr", "fgn")
```

This'll go out in the next version
