### ISSUE TITLE
Strange parameter bleeding in this command....

### ISSUE THREAD

**Issue by markehammons** [lihaoyi/Ammonite#653]
So I was trying to do a ps aux | grep in ammonite, and I wrote:

`%%ps("aux").toString().split("\n").toSeq |? (_.contains("root"))`

and I'd get a result that couldn't possibly be from ps aux...

>   PID TTY          TIME CMD
 8092 pts/5    00:01:44 java
20844 pts/5    00:00:00 ps

tooling around a bit, it seems that somehow, my attempt to pipe data is bleeding into the parameter list for ps!

`%%ps("aux").toString().split("\n").toSeq` | (a => a + "hello")`

> error: format specification must follow o

> Usage:
> ps [options]

> Try 'ps --help <simple|list|output|threads|misc|all>'
> or 'ps --help <s|l|o|t|m|a>'
> for additional help text.

Rewriting as `%%("ps","aux").toString().split("\n").toSeq` | (a => a + "hello")` fixes the issue and gives the expected output, so it seems this is a macro issue.

I'm using ammonite 1.0.0-RC8.

**Comment by lihaoyi** [comment]
Just use `%%('ps, 'aux)`? Seems like a Scala operator precedence problem, which is unfortunate, but I've already updated all the docs when using `%%` to try and follow this style so people won't bump into this. single `%ps 'aux` tends to not have the same problem since it produces no useful return value and so people tend not to use it with operator chains
