### ISSUE TITLE
import URLs

### ISSUE THREAD

**Issue by bblfish** [lihaoyi/Ammonite#655]
I really like the way ammonite can import remote packages from within a script, this makes programming so much easier, as one does not have to set up an environment to do all that work.

But I have a feeling it could be improved, simplified, made more coherent, as well as more secure by using [URI](https://tools.ietf.org/html/rfc3986)s. So here are some initial ideas that I put forward, stemming from experience working with Linked Data and the Semantic Web - [for which I just put together a short tutorial using Ammonite](https://github.com/banana-rdf/banana-rdf/wiki/Scripting-with-Ammonite). This applies here, because files, packages and other resources on the web are just different forms of data. 

Let me just recapitulate some basics that everyone here knows but just to make sure we are on the same page. There are two types of URIs: 
 * URLs: Uniform Resource Locators  starting with schemes such as `http://`, `https://`, `ftp://`, `file://`, ...)  and just simply relative URLs such as `images/doc.jpg` which resolve to different URLs depending on how the document in which it is contained was reached, ie if the above URL was in an html file retrieved from `http://ammonite.io/` then that relative URL is resolved to `http://ammonite.io/images/shell.jpg`. The same file viewed by the web server admin with lynx from a shell open on the server would resolve to `file:///Users/web/www/images.jpg`
 * URNs: Uniform Resource Identifiers starting with schemes such as `urn:isbn:` for books. It would make a lot of sense for Maven identifiers something like `urn:GAV:junit:junit:3.8.1` which [was discussed in this 2010 thread](http://maven.40175.n5.nabble.com/standardized-Maven-GAV-URN-td511480.html)  but I am not sure what the agreement is at this time.

So just as with html where one uses relative urls to edit documents on the local file system and can view them in a browser using the `file://` url and then just `scp` that to a web server and have it work in the browser with an `http` or `https` url it would be nice if one could have the same in ammonite, so that I could run scripts locally using relative urls and then also just publish them and have them work remotely using the full url. 

So, for example, I have now written my first Ammonite script and placed it in my local directory. I should be able to have it call other scripts placed there too. But then when I write about it in my wiki page I should be able to tell people to just run it with

$ amm https://raw.githubusercontent.com/wiki/banana-rdf/banana-rdf/ammonite/Jump.sc

and ammonite be able to follow the links and fetch any dependencies in the same ammonite directory. (There are none for the moment in that file)

Now there seems to be two roles for imports: one is to specify where scala should look for class files, and one to specify which classes to import. Scala currently does only the second, and Ammonite is exploring extending this with the second. I have a feeling these two functions are orthogonal. That would lead me to think of the following syntax

```scala
import banana.jump._ from <https://raw.githubusercontent.com/wiki/banana-rdf/banana-rdf/ammonite/Jump.sc>
import scalaj.http._ from <urn:gav:org.w3::banana-sesame:0.8.4-SNAPSHOT>
import local.wiki.helper from <wiki/helpers.sc>
```

Then as people felt the need for supporting new protocols they could write handlers for the protocols, and also in the case of http, write handlers to deal with the different mimte types and formats that could be returned - I am thinking for example that one could also import maven files by using a URL pointing to [a POM file](http://bblfish.net/work/repo/snapshots/org/w3/banana-rdf_2.12/0.8.4-SNAPSHOT/banana-rdf_2.12-0.8.4-SNAPSHOT.pom) )

I think this could also improve the security of scala code in that for the moment someone could add a file to a maven jar that had a function with the same package name and signature as one the author thought was coming from a different source.

So those are initial ideas that I thought I should write down to see what people make of this. I am not hung up on the particular syntax I invented on the spot above. 

(One could also extend this perhaps with a mention of the hash of the code one wanted to use.)

**Comment by lihaoyi** [comment]
Related https://github.com/lihaoyi/Ammonite/pull/654. Haven't had time to read through this properly, but will do so when I have time

**Comment by lihaoyi** [comment]
> Now there seems to be two roles for imports: one is to specify where scala should look for class files, and one to specify which classes to import. Scala currently does only the second, and Ammonite is exploring extending this with the second. I have a feeling these two functions are orthogonal

Yeah they're basically orthogonal. Ammonite kind of mixes them together a bit in one case, importing a `$file` automatically brings the script-wrapper-object into scope, but I think it's a pretty peripheral (but nice to have!) convenience feature and other magic imports such as `$ivy` or `$cp` do not have that behaviour.

The way I look at it, `$magic` imports are basically the ones that mangle the classpath, while the "normal" imports that follow are the ones that do the real class-importing

> That would lead me to think of the following syntax
> ```scala
> import banana.jump._ from <https://raw.githubusercontent.com/wiki/banana-rdf/banana-rdf/ammonite/Jump.sc>
> import scalaj.http._ from <urn:gav:org.w3::banana-sesame:0.8.4-SNAPSHOT>
> import local.wiki.helper from <wiki/helpers.sc>
> ```

By my current convention, the (imaginary) syntax for these would be something like:

```scala
import $url.`https://raw.githubusercontent.com/wiki/banana-rdf/banana-rdf/ammonite/Jump.sc`, banana.jump._
import $thingy.`urn:gav:org.w3::banana-sesame:0.8.4-SNAPSHOT`, scalaj.http._
import $file.`wiki/helpers.sc`, local.wiki.helper
```

Although again, the last one would be simplified as 

```scala
import $file.wiki.helpers
```

Which I think is a reasonable thing to do 99% of the time

This is basically equivalent to the syntax you proposed, but with one caveat: we are not introducing a new syntax! Or we are, but it's a syntax that's both obviously-new-to-programmers, while also being similar-enough-to-the-old-syntax that tooling such as parsers, IDEs, etc. can pass them through with minimal errors. 

You still get type errors with my current convention in IntelliJ, but with your custom syntax you'd get syntax errors, which tend to cascade much worse throughout the remainder of the file.

> (One could also extend this perhaps with a mention of the hash of the code one wanted to use.)

Yeah, that's something that's worth discussing, but probably not the top priority for Ammonite. This really should be raised as an SBT issue: it doesn't matter at all if Ammonite scripts are made safer with Subresource Integrity Protection if everyone's SBT projects are still vulnerable. There are orders of magnitude more people using SBT than Ammonite, and I think it's safe to say that everyone using Ammonite is also using SBT.

----------------------------------------------------------------

w.r.t. possibly abstracting over different URIs and having uniform handling of them, I personally think that there isn't going to be much value in the uniform handling you proposed. 

Presumably, in order for it to work we'd need to have different implementations for each resource, e.g. in order to make downloading maven jars via `urn:GAV:junit:junit:3.8.1` work. This is *already something we have*, except instead of dispatching based on the URI/URN, we dispatch based on the `$tag` of the magic import. We have one handler for script `$file`s, one for `$ivy` dependencies, and are possibly adding one for HTTP/HTTPS `$url`s. As far as I can tell, what you are proposing is basically isomorphic to what we already have, just with a different syntax.

----------------------------------------------------------------
Lastly,

**Comment by bblfish** [comment]
ok, I agree no need for new syntax at this point. 

Your suggestion:
```scala
$url.`https://raw.githubusercontent.com/wiki/banana-rdf/banana-rdf/ammonite/Jump.sc`, banana.jump._`  
```
is good for now especially if it could also work for relative urls, eg
```scala
$url.`script/wiki.sc`
```
So that one could just push this to a web server without changes and people could run them from the command line. It would be good to incite people to link their files together like this using relative URLs as that would allow one to get to the point where one could point an editor at a local file, and it could find all the docs and dependencies that it needs, without needing to set up a whole project. It would then even make it possible to point one's editor to a remote script, and it would be able to fetch the dependencies and make a local copy of it. Then if one published the file on another server the editor would know exactly which relative URLs to change to which absolute urls to get all the dependencies working again.

I think if people start doing this a lot, then suggestions for better syntaxes will pop up by themselves, and also people will have experience to provide feedback on such proposals.

So I my suggestion would be to get $url to work with relative urls in the right way, and then deprecate $file to get people to do the right thing :-)

**Comment by bblfish** [comment]
It looks like the Thoughtworks plugin has support for $url.

**Comment by lihaoyi** [comment]
Since `import $url` seems to do what you want, just use that I guess
