### ISSUE TITLE
[Feature request] session persistance

### ISSUE THREAD

**Issue by yangguang760** [lihaoyi/Ammonite#702]
It would be great if repl.sess.save() and repl.sess.load() could save/load sessions with files.

**Comment by lihaoyi** [comment]
I don't think this will be possible in the naive case; you can define any Java objects in Ammonite, and Java objects are typically non serializable. Things like classloaders, file handles, etc. 

Ammonite is better than most in that it tends to keep "dumb data" rather than actual file handles lying around, but the stuff *you* define in the REPL can be anything.

This is something that will need some experimentation to see what's possible, spec it out properly and implement. I won't be the one to do it, but feel free to play with Ammonite's code and see what you can put together!
