### ISSUE TITLE
Add script loading command to repl

### ISSUE THREAD

**Issue by sschaef** [lihaoyi/Ammonite#73]
Scalas Repl can load scripts with `:load`. `ammonite.repl.frontend.Load` should supoort this too.

**Comment by lihaoyi** [comment]
Yeah that would be nice. It would be nice to do this in a way that's reasonable. In particular:

- Doesn't interpret/compile lines one by one because it's slow
- Doesn't interpret/compile lines all at once, because you may want earlier lines to e.g. `load.ivy` things that later lines depend on
- Caches compiled blocks based on hash-of-source-code-with-current-context, so that repeated runs can happen fast if there's no change in the script.

Not sure if all these are achievable, but if they could that'd be great.

I'm imagining a `@` delimited file would be an ideal format. e.g.

```scala
// This stuff happens first
load.ivy(...)
load.ivy(...)
@
// This stuff happens later, depending on the modules loaded above
... do stuff with the modules you loaded ...
```

which roughly matches the experience in the REPL, where `@` delimits compilation units.

I have no idea how the clever caching would work

**Comment by sschaef** [comment]
I think all three points could be easily solved if we would have a real Scala interpreter, i.e. an AST/intermediate code evaluator.

**Comment by lihaoyi** [comment]
Yeah but we don't

**Comment by lihaoyi** [comment]
This has landed in trunk, will be in the next release. Thanks @laci37 !
